In [22]:
# temp_converter.py
def c_to_f(c):
    return (c * 9/5) + 32

if __name__ == "__main__":
    c = float(input("Celsius: "))
    print(f"{c}°C = {c_to_f(c):.2f}°F")


Celsius:  99


99.0°C = 210.20°F


In [2]:
# simple_interest.py
def simple_interest(p, r, t):
    si = p * (r/100.0) * t
    return si, p + si

if __name__ == "__main__":
    p = float(input("Principal: "))
    r = float(input("Rate (%): "))
    t = float(input("Time (years): "))
    si, total = simple_interest(p,r,t)
    print(f"Simple Interest: {si:.2f}\nTotal Amount: {total:.2f}")


Principal:  255
Rate (%):  5
Time (years):  7


Simple Interest: 89.25
Total Amount: 344.25


In [3]:
# student_grade.py
def grade_from_percentage(pct):
    if pct >= 75: return "A"
    if pct >= 60: return "B"
    if pct >= 40: return "C"
    return "Fail"

if __name__ == "__main__":
    marks = []
    for i in range(1,6):
        marks.append(float(input(f"Marks for subject {i}: ")))
    total = sum(marks)
    pct = total / 5
    grade = grade_from_percentage(pct)
    print(f"Total: {total}\nPercentage: {pct:.2f}%\nGrade: {grade}")



Marks for subject 1:  50
Marks for subject 2:  25
Marks for subject 3:  45
Marks for subject 4:  32
Marks for subject 5:  45


Total: 197.0
Percentage: 39.40%
Grade: Fail


In [4]:
# list_operations.py
nums = [12, 5, 8, 3, 10, 7]

def main():
    print("Original:", nums)
    print("Largest:", max(nums))
    print("Smallest:", min(nums))
    s = sorted(nums)
    print("Sorted:", s)
    new = int(input("Add a new number: "))
    s.append(new)
    print("After adding:", s)
    removed_evens = [x for x in s if x % 2 != 0]
    print("After removing even numbers:", removed_evens)

if __name__ == "__main__":
    main()


Original: [12, 5, 8, 3, 10, 7]
Largest: 12
Smallest: 3
Sorted: [3, 5, 7, 8, 10, 12]


Add a new number:  5


After adding: [3, 5, 7, 8, 10, 12, 5]
After removing even numbers: [3, 5, 7, 5]


In [5]:
# dict_practice.py
students = {
    "ram": 85,
    "sita": 78,
    "john": 92,
    "meera": 88,
    "kumar": 76
}

if __name__ == "__main__":
    print("Students:", list(students.keys()))
    print("Marks:", list(students.values()))
    avg = sum(students.values()) / len(students)
    print(f"Average marks: {avg:.2f}")

    # Add new
    new_name = input("Add student name (or blank to skip): ").strip()
    if new_name:
        students[new_name] = float(input("Marks: "))
    # Update existing
    upd = input("Update student name (or blank to skip): ").strip()
    if upd:
        students[upd] = float(input("New marks: "))

    print("Updated dictionary:", students)


Students: ['ram', 'sita', 'john', 'meera', 'kumar']
Marks: [85, 78, 92, 88, 76]
Average marks: 83.80


Add student name (or blank to skip):  Jagadeep
Marks:  80
Update student name (or blank to skip):  


Updated dictionary: {'ram': 85, 'sita': 78, 'john': 92, 'meera': 88, 'kumar': 76, 'Jagadeep': 80.0}


In [6]:
# multiplication_table.py
n = int(input("Enter number: "))
for i in range(1, 21):
    print(f"{n} x {i} = {n*i}")


Enter number:  1


1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10
1 x 11 = 11
1 x 12 = 12
1 x 13 = 13
1 x 14 = 14
1 x 15 = 15
1 x 16 = 16
1 x 17 = 17
1 x 18 = 18
1 x 19 = 19
1 x 20 = 20


In [10]:
# count_vowels.py
def count_vowels(s):
    return sum(1 for ch in s if ch.lower() in 'aeiou')

if __name__ == "__main__":
    s = input("Enter string: ")
    print("Vowels count:", count_vowels(s))


Enter string:  Jagadeep


Vowels count: 4


In [9]:
# sum_of_digits.py
def sum_digits(n):
    return sum(int(ch) for ch in str(abs(int(n))) if ch.isdigit())

if __name__ == "__main__":
    n = input("Enter number: ")

    digits = [int(ch) for ch in n if ch.isdigit()]
    print(" + ".join(map(str,digits)), "=", sum_digits(n))


Enter number:  1234


1 + 2 + 3 + 4 = 10


In [11]:
# is_prime.py
import math
def is_prime(n):
    n = int(n)
    if n <= 1: return False
    if n <= 3: return True
    if n % 2 == 0: return False
    r = int(math.isqrt(n))
    for i in range(3, r+1, 2):
        if n % i == 0:
            return False
    return True

if __name__ == "__main__":
    n = int(input("Enter n: "))
    print(is_prime(n))


Enter n:  2


True


In [12]:
# login_system.py
def login(max_attempts=3):
    username = "admin"
    password = "1234"
    attempts = 0
    while attempts < max_attempts:
        u = input("Username: ")
        p = input("Password: ")
        if u == username and p == password:
            print("Login successful")
            return True
        attempts += 1
        print(f"Wrong credentials ({attempts}/{max_attempts})")
    print("Account locked")
    return False

if __name__ == "__main__":
    login()


Username:  Jagadeep
Password:  230726


Wrong credentials (1/3)


Username:  admin
Password:  1234


Login successful


In [13]:
# calculator_extended.py
import math

def add(a,b): return a+b
def sub(a,b): return a-b
def mul(a,b): return a*b
def div(a,b):
    if b==0: raise ZeroDivisionError("Divide by zero")
    return a/b
def sq(a): return a*a
def sqrt(a):
    if a < 0: raise ValueError("Negative")
    return math.sqrt(a)
def power(a,b): return a**b

ops = {
    '+': add, '-': sub, '*': mul, '/': div,
    'sq': sq, 'sqrt': sqrt, 'pow': power
}

if __name__ == "__main__":
    print("Ops: + - * / sq sqrt pow (type exit to quit)")
    while True:
        op = input("Operation: ").strip()
        if op == "exit":
            break
        if op in ('sq','sqrt'):
            a = float(input("a: "))
            print(ops[op](a))
        elif op in ('+','-','*','/','pow'):
            a = float(input("a: ")); b = float(input("b: "))
            print(ops[op](a,b))
        else:
            print("Unknown op")


Ops: + - * / sq sqrt pow (type exit to quit)


Operation:  +
a:  2
b:  3


5.0


Operation:  exit


In [14]:
# guess_game.py
import random

def play():
    diff = input("Difficulty (easy/medium/hard): ").strip().lower()
    if diff == "easy":
        low, high, attempts = 1, 50, 10
    elif diff == "medium":
        low, high, attempts = 1, 100, 7
    else:
        low, high, attempts = 1, 500, 6

    secret = random.randint(low, high)
    for i in range(1, attempts+1):
        try:
            g = int(input(f"Attempt {i}/{attempts} ({low}-{high}): "))
        except ValueError:
            print("Enter integer")
            continue
        if g == secret:
            print("Correct!")
            return
        print("Too low" if g < secret else "Too high")
    print("Out of attempts. The number was", secret)

if __name__ == "__main__":
    play()


Difficulty (easy/medium/hard):  hard
Attempt 1/6 (1-500):  299


Too high


Attempt 2/6 (1-500):  150


Too low


Attempt 3/6 (1-500):  200


Too low


Attempt 4/6 (1-500):  250


Too high


Attempt 5/6 (1-500):  225


Too high


Attempt 6/6 (1-500):  220


Too high
Out of attempts. The number was 218


In [15]:
# password_checker.py
import re

def rating(pw):
    score = 0
    if len(pw) > 8: score += 1
    if re.search(r'[A-Z]', pw): score += 1
    if re.search(r'\d', pw): score += 1
    if re.search(r'[!@#$%^&*()_+\-=\[\]{};\'\\:"|<,./<>?]', pw): score += 1
    if score <= 1: return "⭐ Weak"
    if score == 2: return "⭐⭐ Medium"
    return "⭐⭐⭐ Strong"

if __name__ == "__main__":
    pw = input("Enter password: ")
    print(rating(pw))


Enter password:  1234


⭐ Weak


In [ ]:
# fortune_teller.py
import random
import datetime
F = {
    "Health": ["A healthy habit will begin this week.", "Rest will improve your focus."],
    "Career": ["An opportunity to learn appears soon.", "Networking will bring a new lead."],
    "Love": ["A kind gesture will warm someone's heart.", "Listen more — it helps relationships."],
    "Finance": ["Small savings add up this month.", "Avoid impulse purchases this week."]
}

def predict(category):
    return random.choice(F.get(category, ["Fortune unclear."]))

if __name__ == "__main__":
    name = input("Your name: ").strip().title()
    print(f"Hello {name}!")
    cat = random.choice(list(F.keys()))
    print(f"Category: {cat}")
    p = predict(cat)
    time = datetime.datetime.now().isoformat()
    record = f"{time} | {name} | {cat} | {p}\n"
    print("Prediction:", p)
    with open("predictions.txt", "a", encoding="utf-8") as f:
        f.write(record)
    print("Saved to predictions.txt")


In [26]:
# numpy_reshape_stack_split.py
import numpy as np

def reshape_examples():
    arr = np.arange(1,17)
    a4x4 = arr.reshape(4,4)
    a2x8 = arr.reshape(2,8)
    a8x2 = arr.reshape(8,2)
    return a4x4, a2x8, a8x2

def stack_examples():
    a = np.array([[1,2],[3,4]])
    b = np.array([[5,6],[7,8]])
    h = np.hstack((a,b))
    v = np.vstack((a,b))
    # add column of zeros
    col0 = np.zeros((a.shape[0],1), dtype=int)
    a_with_col0 = np.hstack((a, col0))
    # add row of ones
    row1 = np.ones((1, a.shape[1]+1), dtype=int)
    a_with_row1 = np.vstack((a_with_col0, row1))
    return h, v, a_with_col0, a_with_row1

def split_examples():
    m = np.arange(1,37).reshape(6,6)
    horiz = np.split(m, 2, axis=0)  # 2 equal horizontal
    vert3 = np.split(m, 3, axis=1)  # 3 equal vertical
    quad = [m[:3,:3], m[:3,3:], m[3:,:3], m[3:,3:]]
    return m, horiz, vert3, quad

def boolean_filtering():
    arr = np.arange(1,31)
    evens = arr[arr % 2 == 0]
    mult5 = arr[arr % 5 == 0]
    gt20 = arr[arr > 20]
    return evens, mult5, gt20

if __name__ == "__main__":
    print("Reshape:", *reshape_examples(), sep="\n\n")
    print("\nStack examples:", *stack_examples(), sep="\n\n")
    print("\nSplit examples:", *split_examples(), sep="\n\n")
    print("\nBoolean filtering:", *boolean_filtering(), sep="\n\n")


Reshape:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

Stack examples:

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 0]
 [3 4 0]]

[[1 2 0]
 [3 4 0]
 [1 1 1]]

Split examples:

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])]

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22],
       [27, 28],
       [33, 34]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24],
       [29, 30],
       [35, 36]])]

[array([[ 1,  2

In [27]:
# emoji_generator.py
import random
EMOJI = ['😀','😂','🤖','🔥','🌟','✨','🍀','🎉','🤩','😎']
if __name__ == "__main__":
    n = int(input("How many emojis? "))
    print(" ".join(random.choice(EMOJI) for _ in range(n)))


How many emojis?  13


😎 🌟 ✨ 😀 🍀 🤖 🍀 🌟 😎 ✨ 🎉 🤖 🎉


In [24]:
# todo_manager.py
import json, os
FILE = "todo.json"

def load():
    if not os.path.exists(FILE): return []
    with open(FILE,'r') as f: return json.load(f)

def save(items):
    with open(FILE,'w') as f: json.dump(items, f, indent=2)

def main():
    items = load()
    while True:
        cmd = input("Add/View/Delete/Exit: ").strip().lower()
        if cmd == "add":
            t = input("Task: ")
            items.append(t)
            save(items)
            print("Added.")
        elif cmd == "view":
            for i,t in enumerate(items,1): print(i, t)
        elif cmd == "delete":
            idx = int(input("Index to delete: "))
            if 1 <= idx <= len(items):
                items.pop(idx-1)
                save(items)
                print("Deleted.")
            else:
                print("Invalid index")
        elif cmd == "exit":
            break
        else:
            print("Unknown command")

if __name__ == "__main__":
    main()


Add/View/Delete/Exit:  Add
Task:  hi


Added.


Add/View/Delete/Exit:  view


1 hi


Add/View/Delete/Exit:  hi


Unknown command


Add/View/Delete/Exit:  hi


Unknown command


Add/View/Delete/Exit:  view


1 hi


Add/View/Delete/Exit:  Add
Task:  hellO


Added.


Add/View/Delete/Exit:  View


1 hi
2 hellO


Add/View/Delete/Exit:  Exit
